language:
  ruby

rvm:
  - '2.0.0'
  - '2.1.1'
  - '2.4.4'
  - '2.5.1'
  - jruby-head
#  - rbx-2.1.1
script:
  bundle exec rspec 
  
before_install:
  - sudo apt-get update -qq
  - sudo apt-get install -y r-base r-base-dev
